
[package]
name = "my_macros"
version = "0.1.0"
edition = "2021"

# This is the crucial part that tells Cargo it's a procedural macro crate
[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
